server:
    port: 8080

app:
    health:
        directory: /health
    nextcloud:
        url: ${NEXTCLOUD_URL}
        username: ${NEXTCLOUD_USERNAME}
        token: ${NEXTCLOUD_TOKEN}
        dav-path: /remote.php/dav/files/

spring:
    application:
        name: ms-recopilador
    datasource:
        url: ${DB_URL}
        username: ${DB_USERNAME}
        password: ${DB_PASSWORD}
        driver-class-name: org.mariadb.jdbc.Driver

    jpa:
        database-platform: org.hibernate.dialect.MariaDBDialect
        hibernate:
            ddl-auto: update
        show-sql: false