spring:
  application:
    name: ms-recopilador
  datasource:
    url: jdbc:mariadb://192.168.68.195:3306/develop
    username: apps
    password: apps
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: update
    show-sql: false

  server:
    port: 8080
