name: deploy_pull_request

on:
  pull_request:
    branches: [ "master" ]

permissions: write-all

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: ${{ github.event.repository.name }}
      VERSION: latest

    steps:
    # loggear las env
    - name: Log env
      run: echo ${{ env.IMAGE_NAME }}:${{ env.VERSION }}


    - name: Check out the repository
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
